services:
  app:
    build: .
    container_name: api_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: shared-app-network